### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by WhosDatPizzaGuy** [sneakyevilSK/ImGuiMMenu#1]
this may just come off really stupid to you, but if you can help it would be great
I'm getting errors in include.hpp 

no operator "+" matches these operands
and 
no operator "-" matches these operands

i have tried using google but nothing on this 

if you can help thank you

**Comment by sneakyevil** [comment]
Read imgui docs & faq: https://github.com/ocornut/imgui/blob/7e03ae32403f85f6c86f0c884a8243e2e14e483f/docs/FAQ.md#q-how-can-i-use-maths-operators-with-imvec2
