### ISSUE TITLE
[Bug Fix] Fix arrow icon overriding imgui fonts

### ISSUE THREAD

**Issue by RHAtUAT** [sneakyevilSK/ImGuiMMenu#3]
// Call this after ImGui_ImplWin32_Init & ImGui_[BackEnd_Renderer]_Init...
        bool Initialize()
        {
            ImGuiIO* m_IO = &ImGui::GetIO();

            // The first font added here is pushed to the global font variable across all of ImGUI
            // if you want to only use the font for the menu and not the defualt Imgui elements then you need to add the line 
            // 
            // Imgui::PushFont(Font.Primary); 
            // 
            // before the return statement in the Begin() function and 
            // 
            // ImGui::PopFont();
            // 
            // at the end of the End() function.
            // 
            // This ensures that the font is only loaded for the duration the menu is rendering. 
            // Otherwise, if you were to load, for example, the Icons.Font first, then that font, which is actually just an arrow icon, would decome the default font for all the ImGui elements.
            // This is because m_IO is a pointer to GetIO(), so we're directly updating the memory address of the Font ImGui uses instead of creating a new instance of a Font variable.
            
            // Fonts
            Font.Primary = m_IO->Fonts->AddFontFromMemoryCompressedTTF(ImGuiMenu::Font::Primary_Data, ImGuiMenu::Font::Primary_SizeData, CalcDPI(16.f));
            Font.Header = m_IO->Fonts->AddFontFromMemoryCompressedTTF(ImGuiMenu::Font::Header_Data, ImGuiMenu::Font::Header_SizeData, CalcDPI(32.f));

            // Icons
            Icons.Font = m_IO->Fonts->AddFontFromMemoryCompressedTTF(ImGuiMenu::Font::Icons_Data, ImGuiMenu::Font::Icons_SizeData, CalcDPI(16.f));
            if (!Icons.Initialize())
                return false;

            if (!Font.AllLoaded())
                return false;

            // Sizes
            m_Pos = ImVec2(0.05f, 0.05f);
            m_FrameWidth = CalcDPI(420.f);

            Header.m_Height = CalcDPI(85.f);

            // Push the custom font to the imgui font variable when the menu begins rendering
            //ImGui::PushFont(Font.Primary);

            return true;
        }

**Comment by RHAtUAT** [comment]
Also make sure to add

```
            // Uncomment if you want to limit the custom font to just this menu instead of all imgui elements
            //ImGui::PopFont();
```
            
to the bottom of the end function

**Comment by sneakyevil** [comment]
This isn't a bug. You just need to Add default font before calling initilization function. Doing push and pop each frame is just pointless overhead for calling function.
